/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registration_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class College extends javax.swing.JFrame {
    Connection conn = ConnectDB.Connect();
    PreparedStatement ps = null;
    ResultSet rs = null;
    Functions f = new Functions();
    String strDashLine = "--------------------";
    
    
    public void setFieldsEditable(boolean blFlag){
        txtCollegeCode.setEditable(blFlag);
        txtDescription.setEditable(blFlag);
        dtcDateOpened.setEnabled(blFlag);
        dtcDateClosed.setEnabled(blFlag);
        cmbStatus.setEnabled(blFlag);
    }
    public void setStatus(String status){
        cmbStatus.removeAllItems();        
        cmbStatus.addItem("Active");
        cmbStatus.addItem("Inactive");
        if(status.equals("A")){
            cmbStatus.setSelectedItem("Active");
        } else if(status.equals("I")){
            cmbStatus.setSelectedItem("Inactive");
        } 
    }
    
    public void clearForms(){
        txtCollegeCode.setText(null);
        txtDescription.setText(null);
        dtcDateOpened.setDate(null);
        dtcDateClosed.setDate(null);
        setStatus("A");
        
    }
    public boolean isFieldValidated(){
        boolean blFlag = true, blIsEmpty = true, blIsValidDate = true;
        //college code
        if(f.isEmpty(txtCollegeCode.getText())){
            blIsEmpty = false;
            lblInvCC.setVisible(true);
        }
        else if(!f.isValidCollegeCode(txtCollegeCode.getText())){
            blFlag = false;
            JOptionPane.showMessageDialog(null, "Please enter a valid College Code. (Letters, spaces and numbers only, up to 10 characters)", "Error", JOptionPane.ERROR_MESSAGE);
        }
        //description
        if(f.isEmpty(txtDescription.getText())){
            blIsEmpty = false;
            lblInvDesc.setVisible(true);
        } else if(!f.isValidDescription(txtDescription.getText())){
            lblInvDesc.setVisible(true);
            blFlag = false;
            JOptionPane.showMessageDialog(null, "Please enter a valid Description (letters and spaces only, up to 100 characters).", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        //date opened
        try{
            new SimpleDateFormat("yyyy-MM-dd").format(dtcDateOpened.getDate());
        } catch(Exception e){
            lblInvDateOpen.setVisible(true);
            blFlag = false;
            blIsValidDate = false;
        }
        
        //date closed
        try{
            new SimpleDateFormat("yyyy-MM-dd").format(dtcDateClosed.getDate());
        } catch(Exception e){
            lblInvDateClosed.setVisible(true);
            blFlag = false;
            
        }
        
        if(!blIsEmpty){
            JOptionPane.showMessageDialog(null, "Fields shouldn't be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            blFlag = false;
        }
        if(!blIsValidDate){
            JOptionPane.showMessageDialog(null, "Please enter a valid date", "Error", JOptionPane.ERROR_MESSAGE);
            blFlag = false;
        }
        return blFlag;
    }
    
    public void removeError(){
        lblInvCC.setVisible(false);
        lblInvDesc.setVisible(false);
        lblInvDateOpen.setVisible(false);
        lblInvDateClosed.setVisible(false);
        lblInvStatus.setVisible(false);
    }

    /**
     * Creates new form College
     */
    public College() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dtcDateClosed = new com.toedter.calendar.JDateChooser();
        dtcDateOpened = new com.toedter.calendar.JDateChooser();
        txtCollegeCode = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtDescription = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblInvCC = new javax.swing.JLabel();
        lblInvDesc = new javax.swing.JLabel();
        lblInvDateOpen = new javax.swing.JLabel();
        lblInvDateClosed = new javax.swing.JLabel();
        lblInvStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblForms = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("College Code");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Description");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Date opened");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Date closed");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Status");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.setEnabled(false);
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("View College Information");

        lblInvCC.setForeground(new java.awt.Color(255, 51, 51));
        lblInvCC.setText("*");

        lblInvDesc.setForeground(new java.awt.Color(255, 51, 51));
        lblInvDesc.setText("*");

        lblInvDateOpen.setForeground(new java.awt.Color(255, 51, 51));
        lblInvDateOpen.setText("*");

        lblInvDateClosed.setForeground(new java.awt.Color(255, 51, 51));
        lblInvDateClosed.setText("*");

        lblInvStatus.setForeground(new java.awt.Color(255, 51, 51));
        lblInvStatus.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirm)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(130, 130, 130))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCollegeCode)
                    .addComponent(txtDescription)
                    .addComponent(dtcDateOpened, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtcDateClosed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvStatus))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvDateOpen))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvDateClosed))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvDesc))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvCC))
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblInvCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblInvDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblInvDateOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtcDateOpened, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblInvDateClosed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtcDateClosed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblInvStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnConfirm))
                .addGap(19, 19, 19))
        );

        tblForms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblForms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFormsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblForms);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void refreshTable(){
        try{
            ps = conn.prepareStatement("Select * from oop23.College");
            rs = ps.executeQuery();
            tblForms.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            f.displayError(e);
        }
    }
    private void tblFormsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFormsMouseClicked
        // TODO add your handling code here:
        int intRow = tblForms.getSelectedRow();
        String strCollegeCode = "";
        strCollegeCode = tblForms.getValueAt(intRow, 0).toString();
        setFieldsEditable(false);
        try{
                ps = conn.prepareStatement("Select * FROM oop23.college WHERE college_code = '" + strCollegeCode + "';");
                rs = ps.executeQuery();
                if(rs.next()){
                    txtCollegeCode.setText(rs.getString("college_code"));
                    txtDescription.setText(rs.getString("description"));
                    dtcDateOpened.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString("date_opened")));
                    dtcDateClosed.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString("date_closed")));
                    setStatus(rs.getString("status"));
                    //new rs
                }
            }
            catch(Exception e) {
                f.displayError(e);
            }
    }//GEN-LAST:event_tblFormsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        btnConfirm.setEnabled(true);
        btnCancel.setEnabled(true);
        txtCollegeCode.setEditable(true);
        clearForms();
        setFieldsEditable(true);
        removeError();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        btnAdd.setEnabled(false);
        btnDelete.setEnabled(false);
        btnConfirm.setEnabled(true);
        btnCancel.setEnabled(true);
        removeError();
        setFieldsEditable(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        btnEdit.setEnabled(false);
        btnAdd.setEnabled(false);
        btnConfirm.setEnabled(true);
        btnCancel.setEnabled(true);
        txtCollegeCode.setEditable(true);
        removeError();
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void resetButtons(){
        btnEdit.setEnabled(true);
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(true);
        btnCancel.setEnabled(false);
        btnConfirm.setEnabled(false);
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        resetButtons();
        setFieldsEditable(false);
        removeError();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        removeError();
        if(btnAdd.isEnabled() && isFieldValidated() ){
            addCollege();
            return;
        }
        if(btnEdit.isEnabled() && isFieldValidated() ){
            editCollege();
            return;
        }
        if(btnDelete.isEnabled()){
            if(f.isEmpty(txtCollegeCode.getText()) || !f.isValidCollegeCode(txtCollegeCode.getText())){
                JOptionPane.showMessageDialog(null, "Please enter a valid College Code (Letters, numbers and spaces only, upto 10 characters).", "Error", JOptionPane.ERROR_MESSAGE);
                lblInvCC.setVisible(true);
                return;
            }
            deleteCollege();
            return;
        }

    }//GEN-LAST:event_btnConfirmActionPerformed
    public void addCollege(){
        String strStatus = f.toStatus(cmbStatus.getSelectedItem().toString());
        int intAnswer = JOptionPane.showConfirmDialog(null, "Do you really want to add? ", "confirm",JOptionPane.YES_NO_OPTION);
        if(intAnswer == 0){
            try{
                ps = conn.prepareStatement("INSERT INTO oop23.college VALUES ('"
                    +txtCollegeCode.getText()
                    +"', '"+txtDescription.getText()
                    +"', '"+new SimpleDateFormat("yyyy-MM-dd").format(dtcDateOpened.getDate())
                    +"', '"+new SimpleDateFormat("yyyy-MM-dd").format(dtcDateClosed.getDate())
                    +"', '"+ strStatus
                    +"')");
                ps.execute();
                JOptionPane.showMessageDialog(null, "Addition is successful.");
                resetButtons();
                removeError();
                refreshTable();
                setFieldsEditable(false);
            } catch(Exception e) {
                    System.out.println(e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Addition is aborted");
        }
    }
    public void editCollege(){
        String strStatus = f.toStatus(cmbStatus.getSelectedItem().toString());
        int intAnswer = JOptionPane.showConfirmDialog(null, "Do you really want to edit? ", "confirm",JOptionPane.YES_NO_OPTION);
        if(intAnswer == 0){
            try{
            ps = conn.prepareStatement("UPDATE oop23.college SET description = '"
                +txtDescription.getText()
                +"', date_opened = '" + new SimpleDateFormat("yyyy-MM-dd").format(dtcDateOpened.getDate())
                +"', date_closed = '" + new SimpleDateFormat("yyyy-MM-dd").format(dtcDateClosed.getDate())
                +"', status = '" + strStatus
                +"'"
                +" WHERE college_code = '" + txtCollegeCode.getText()
                +"'");
            ps.execute();
            JOptionPane.showMessageDialog(null, "Edit is successful.");
            resetButtons();
            removeError();
            refreshTable();
            setFieldsEditable(false);
            }catch(Exception e) {
                f.displayError(e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Edit is aborted");
        }
    }
    public void deleteCollege(){
        int intAnswer = JOptionPane.showConfirmDialog(null, "Do you really want to delete? ", "confirm",JOptionPane.YES_NO_OPTION);
        if(intAnswer == 0){
            try{
            ps = conn.prepareStatement("DELETE FROM oop23.college"
                +" WHERE college_code = '"
                +txtCollegeCode.getText()
                +"' AND date_opened = '"+new SimpleDateFormat("yyyy-MM-dd").format(dtcDateOpened.getDate())
                +"' AND date_closed = '"+new SimpleDateFormat("yyyy-MM-dd").format(dtcDateClosed.getDate())
                +"'");   
            ps.execute();
            JOptionPane.showMessageDialog(null, "Edit is successful.");
            resetButtons();
            removeError();
            refreshTable();
            clearForms();
            setFieldsEditable(false);
            }catch(Exception e) {
                f.displayError(e);
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Deletion is aborted");
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        refreshTable();
        removeError();
        setFieldsEditable(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(College.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(College.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(College.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(College.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new College().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbStatus;
    private com.toedter.calendar.JDateChooser dtcDateClosed;
    private com.toedter.calendar.JDateChooser dtcDateOpened;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInvCC;
    private javax.swing.JLabel lblInvDateClosed;
    private javax.swing.JLabel lblInvDateOpen;
    private javax.swing.JLabel lblInvDesc;
    private javax.swing.JLabel lblInvStatus;
    private javax.swing.JTable tblForms;
    private javax.swing.JTextField txtCollegeCode;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
