/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registration_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author John Bryan
 */
public class EnrollWindow extends javax.swing.JFrame {
    Connection conn = ConnectDB.Connect();
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form EnrollWindow
     */
    public EnrollWindow() {
        initComponents();
    }
    String strStudentNum = "", strCourseCode = "", strCollegeCode = "", strBlockCode = ""
            , strBlockNo = "", strSchoolYear= "", strSemester = "", strRemarkGrade = "";
    String[] arrSubjects = new String[17];
    int intYear = 0;
    //private final double[] specifiedGrades = {1.00, 1.25, 1.50, 1.75, 2.00, 2.25, 2.50, 2.75, 3.00, 5.00};
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelNotEnrolled = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSY = new javax.swing.JLabel();
        cmbSchoolYear = new javax.swing.JComboBox<>();
        lblSem = new javax.swing.JLabel();
        cmbSemester = new javax.swing.JComboBox<>();
        lblStudentNo = new javax.swing.JLabel();
        btnEnroll = new javax.swing.JButton();
        lblCourseCode = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        lblCollegeCode = new javax.swing.JLabel();
        txtStudentNo = new javax.swing.JTextField();
        txtCourseCode = new javax.swing.JTextField();
        txtCollegeCode = new javax.swing.JTextField();
        lblFail = new javax.swing.JLabel();
        lblAlreadyEnrolled = new javax.swing.JLabel();
        lblCannotEnroll = new javax.swing.JLabel();
        panelEnrolled = new javax.swing.JPanel();
        lblSY2 = new javax.swing.JLabel();
        lblSem2 = new javax.swing.JLabel();
        lblStudentNo2 = new javax.swing.JLabel();
        lblCourseCode2 = new javax.swing.JLabel();
        lblCollegeCode1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtEnrolledStudentNo = new javax.swing.JTextField();
        txtEnrolledCourseCode = new javax.swing.JTextField();
        txtEnrolledBlock = new javax.swing.JTextField();
        txtEnrolledSY = new javax.swing.JTextField();
        txtEnrolledSem = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNotEnrolled.setBackground(new java.awt.Color(255, 255, 255));
        panelNotEnrolled.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enroll For");
        panelNotEnrolled.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblSY.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSY.setText("School Year :");
        panelNotEnrolled.add(lblSY, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        cmbSchoolYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSchoolYear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSchoolYearItemStateChanged(evt);
            }
        });
        panelNotEnrolled.add(cmbSchoolYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 110, -1));

        lblSem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSem.setText("Semester :");
        panelNotEnrolled.add(lblSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        cmbSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSemester.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSemesterItemStateChanged(evt);
            }
        });
        panelNotEnrolled.add(cmbSemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        lblStudentNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStudentNo.setText("Student No.");
        panelNotEnrolled.add(lblStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnEnroll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnroll.setText("Enroll Now");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });
        panelNotEnrolled.add(btnEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        lblCourseCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCourseCode.setText("Course Code:");
        panelNotEnrolled.add(lblCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lblMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMessage.setText("Enrollment successful!");
        panelNotEnrolled.add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lblCollegeCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCollegeCode.setText("College Code:");
        panelNotEnrolled.add(lblCollegeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txtStudentNo.setText("0000-0000");
        panelNotEnrolled.add(txtStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        txtCourseCode.setText("Text");
        panelNotEnrolled.add(txtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 110, -1));

        txtCollegeCode.setText("Text");
        panelNotEnrolled.add(txtCollegeCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, -1));

        lblFail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFail.setForeground(new java.awt.Color(255, 0, 0));
        lblFail.setText("You have incomplete or failing grade ");
        panelNotEnrolled.add(lblFail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        lblAlreadyEnrolled.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlreadyEnrolled.setForeground(new java.awt.Color(255, 0, 0));
        lblAlreadyEnrolled.setText("You are already enrolled in that SY and Sem ");
        panelNotEnrolled.add(lblAlreadyEnrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        lblCannotEnroll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCannotEnroll.setForeground(new java.awt.Color(255, 0, 0));
        lblCannotEnroll.setText("Cannot Enroll");
        panelNotEnrolled.add(lblCannotEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jPanel2.add(panelNotEnrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, 570));

        panelEnrolled.setBackground(new java.awt.Color(204, 255, 255));
        panelEnrolled.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSY2.setText("School Year :");
        panelEnrolled.add(lblSY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lblSem2.setText("Semester :");
        panelEnrolled.add(lblSem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        lblStudentNo2.setText("Student No.");
        panelEnrolled.add(lblStudentNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lblCourseCode2.setText("Course Code");
        panelEnrolled.add(lblCourseCode2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lblCollegeCode1.setText("Block No.");
        panelEnrolled.add(lblCollegeCode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel10.setText("YOU ARE CURRENTLY ENROLLED");
        panelEnrolled.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        txtEnrolledStudentNo.setText("0000-0000");
        panelEnrolled.add(txtEnrolledStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 90, -1));

        txtEnrolledCourseCode.setText("Text");
        panelEnrolled.add(txtEnrolledCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, -1));

        txtEnrolledBlock.setText("Text");
        panelEnrolled.add(txtEnrolledBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 90, -1));

        txtEnrolledSY.setText("jTextField1");
        txtEnrolledSY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrolledSYActionPerformed(evt);
            }
        });
        panelEnrolled.add(txtEnrolledSY, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 90, -1));

        txtEnrolledSem.setText("jTextField2");
        panelEnrolled.add(txtEnrolledSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, -1));

        jPanel2.add(panelEnrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 320, 570));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration_system/bg_plm_2.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1110, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cmbSchoolYear.removeAllItems();
        cmbSemester.removeAllItems();
        txtStudentNo.setText(strStudentNum);
        txtStudentNo.setEditable(false);
        txtCourseCode.setEditable(false);
        txtCollegeCode.setEditable(false);
        txtEnrolledStudentNo.setEditable(false);
        txtEnrolledSY.setEditable(false);
        txtEnrolledSem.setEditable(false);
        txtEnrolledCourseCode.setEditable(false);
        txtEnrolledBlock.setEditable(false);
        lblFail.setVisible(false);
        try{
            //Get all School Year
            ps = conn.prepareStatement("SELECT * FROM oop23.sy");
            rs = ps.executeQuery();
            while(rs.next()){
                cmbSchoolYear.addItem(rs.getString("sy"));
            }
            //Get all semester
            ps = conn.prepareStatement("SELECT * FROM oop23.semester");
            rs = ps.executeQuery();
            while(rs.next()){
                cmbSemester.addItem(rs.getString("semester"));
            }
            //Check what course of the student        
            ps = conn.prepareStatement("SELECT course_code FROM oop23.student"
                    + " WHERE student_no = '"+strStudentNum
                    + "'");
            rs = ps.executeQuery();
            if(rs.next()){
                strCourseCode = rs.getString("course_code");
                if(strCourseCode.equals("BSCS-CS")){
                    strCollegeCode = "COE"; 
                }else{
                    strCollegeCode = "COE";
                }
                txtCourseCode.setText(strCourseCode);
            }
            txtCollegeCode.setText(strCollegeCode);
            lblMessage.setVisible(false);
        }catch(Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_formWindowOpened

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
        strSchoolYear = cmbSchoolYear.getSelectedItem().toString().trim();
        strSemester = cmbSemester.getSelectedItem().toString().trim();
        try{
            if(!strCourseCode.equals("BSCS-CS") && !strCourseCode.equals("BSCS-IT")){
                lblCannotEnroll.setVisible(true);
                return;
            }
            //Check if student is currently enrolled in that semester and school year
            ps = conn.prepareStatement("SELECT COUNT(*) AS COUNT FROM oop23.grade"
                    + " WHERE sy = '"+strSchoolYear
                    + "' AND semester = '"+strSemester
                    + "' AND student_no = '"+strStudentNum
                    + "'");
            rs = ps.executeQuery();
            rs.next();
            int count = rs.getInt("count");
            
            if (count > 0) {
                lblAlreadyEnrolled.setVisible(true);
                return;
            }
            
            //Check if there's a fail grade in previous semester
            ps = conn.prepareStatement("SELECT COUNT(*) AS COUNT FROM oop23.vwgrade WHERE "
                + "student_no = '"+strStudentNum
               // + "' AND sy = '"+strSchoolYear
                + "' AND (remark = 'Failed' OR remark = 'Incomplete')");
            rs = ps.executeQuery();
            rs.next();
            int failedCount = rs.getInt("count");

                if (failedCount > 0) {
                    lblCannotEnroll.setVisible(true);
                    lblFail.setVisible(true);
                    return;
                }

            String[] strStud = strStudentNum.split("-");
            String strStudentYear = strStud[0];
            int intStudentYear = Integer.parseInt(strStudentYear);
            String[] strSYear = strSchoolYear.split("-");
            String strSyear = strSYear[0];
            int intSY = Integer.parseInt(strSyear);
            intYear = (intSY - intStudentYear) + 1;
            
            if(intStudentYear != 2023){
                // Student cannot enroll if not in the year 2023
                lblCannotEnroll.setVisible(true);
                return;
            }
            int intSem = Integer.parseInt(strSemester);
            if(intSY != 2023 || intSem != 1){
                ps = conn.prepareStatement("SELECT COUNT(*) AS COUNT FROM oop23.vwgrade WHERE "
                + "student_no = '"+strStudentNum
                + "'");
                rs = ps.executeQuery();
                rs.next();
                int intIsEnrolled = rs.getInt("count");

                if (intIsEnrolled == 0) {
                    lblCannotEnroll.setVisible(true);
                    return;
                }    
            }
            
            if("BSCS-CS".equals(strCourseCode)){
            //Randomize block
                int intBlockNo = (int) (Math.random() * 3) + 1;
                strBlockCode = "CS" + intYear + intBlockNo;
            } else if("BSCS-IT".equals(strCourseCode)){
                int intBlockNo = (int) (Math.random() * 3) + 1;
                strBlockCode = "IT" + intYear +intBlockNo;
            }
            strBlockNo = strBlockCode;
            //Get all subjects and store in array
            ps = conn.prepareStatement("SELECT subject_code FROM oop23.subject_schedule"
                    + " WHERE sy = '" +strSchoolYear
                    + "' AND semester = '" +strSemester
                    + "' AND college_code = '"+strCollegeCode
                    + "' AND block_no = '"+strBlockNo
                    + "'");
            rs = ps.executeQuery();
            int i=0;
            while(rs.next() && i < arrSubjects.length){
                    String strSubjectCode = rs.getString("subject_code");
                    arrSubjects[i] = strSubjectCode;
                    i++;      
            }
            //Insert the student in to grade
            for(int j = 0; j<i;j++){
                //int randomIndex = (int) (Math.random() * 9);
                //double randomGrade = specifiedGrades[randomIndex];
                ps = conn.prepareStatement("INSERT IGNORE INTO oop23.grade VALUES ('"
                        +strSchoolYear
                        +"','"+strSemester
                        +"','"+strStudentNum
                        +"','"+arrSubjects[j]
                        +"','"+strBlockCode
                        +"','0.00" //Randomize grade
                        + "')");
                ps.executeUpdate();
            }lblMessage.setVisible(true);
        }catch(Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void txtEnrolledSYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrolledSYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrolledSYActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        txtStudentNo.setText(strStudentNum);
        txtEnrolledStudentNo.setText(strStudentNum);
        txtEnrolledSY.setText(strSchoolYear);
        txtEnrolledSem.setText(strSemester);
        txtEnrolledCourseCode.setText(strCourseCode);
        txtEnrolledBlock.setText(strBlockNo);
        panelEnrolled.setVisible(false);
        lblMessage.setVisible(false);
        lblAlreadyEnrolled.setVisible(false);
        lblCannotEnroll.setVisible(false);
        lblFail.setVisible(false);
        studentCourseCollege();
        try{
            /*ps = conn.prepareStatement("SELECT COUNT(*) AS COUNT FROM oop23.grade"
                    + " WHERE"
                    + " student_no = '"+strStudentNum
                    + "'");
            rs = ps.executeQuery();
            if(rs.next()){
            int count = rs.getInt("count");
                
            if (count == 0) {
                panelNotEnrolled.setVisible(true);
                panelEnrolled.setVisible(false);
            }else{
                panelNotEnrolled.setVisible(false);
                panelEnrolled.setVisible(true);
                }
            }*/
        }catch(Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_formWindowActivated

    private void cmbSchoolYearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSchoolYearItemStateChanged
        // TODO add your handling code here:
        lblFail.setVisible(false);
        lblAlreadyEnrolled.setVisible(false);
        lblMessage.setVisible(false);
        lblCannotEnroll.setVisible(false);
    }//GEN-LAST:event_cmbSchoolYearItemStateChanged

    private void cmbSemesterItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSemesterItemStateChanged
        // TODO add your handling code here:
        lblFail.setVisible(false);
        lblAlreadyEnrolled.setVisible(false);
        lblMessage.setVisible(false);
        lblCannotEnroll.setVisible(false);
    }//GEN-LAST:event_cmbSemesterItemStateChanged
    public void studentCourseCollege(){
        try{
            ps = conn.prepareStatement("SELECT course_code FROM oop23.student"
                    + " WHERE student_no = '"+strStudentNum
                    + "'");
            rs = ps.executeQuery();
            rs.next();
            strCourseCode = rs.getString("course_code");
            txtCourseCode.setText(strCourseCode);
            
            ps = conn.prepareStatement("SELECT college_code FROM oop23.course"
                    + " WHERE course_code = '"+strCourseCode
                    + "'");
            rs = ps.executeQuery();
            rs.next();
            strCollegeCode = rs.getString("college_code");
            txtCollegeCode.setText(strCollegeCode);
        }catch(Exception e) {
                System.out.println(e);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnrollWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JComboBox<String> cmbSchoolYear;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAlreadyEnrolled;
    private javax.swing.JLabel lblCannotEnroll;
    private javax.swing.JLabel lblCollegeCode;
    private javax.swing.JLabel lblCollegeCode1;
    private javax.swing.JLabel lblCourseCode;
    private javax.swing.JLabel lblCourseCode2;
    private javax.swing.JLabel lblFail;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSY;
    private javax.swing.JLabel lblSY2;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblSem2;
    private javax.swing.JLabel lblStudentNo;
    private javax.swing.JLabel lblStudentNo2;
    private javax.swing.JPanel panelEnrolled;
    private javax.swing.JPanel panelNotEnrolled;
    private javax.swing.JTextField txtCollegeCode;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextField txtEnrolledBlock;
    private javax.swing.JTextField txtEnrolledCourseCode;
    private javax.swing.JTextField txtEnrolledSY;
    private javax.swing.JTextField txtEnrolledSem;
    private javax.swing.JTextField txtEnrolledStudentNo;
    private javax.swing.JTextField txtStudentNo;
    // End of variables declaration//GEN-END:variables
}
