/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registration_system;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Regienald
 */
public class LoginMenu extends javax.swing.JFrame {
    Connection conn = ConnectDB.Connect();
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form registration_menu
     */
    public LoginMenu() {
        initComponents();
    }
    StudentMainMenu smm = new StudentMainMenu(); 
    EnrollWindow enw = new EnrollWindow();
    EmployeeMainMenu emm = new EmployeeMainMenu();
    String strID = "";
    String strSelectState = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbSelectStudentEmployee = new javax.swing.JComboBox<>();
        lblStudentNo = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblStudentEmployee = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1365, 765));
        setResizable(false);
        setSize(new java.awt.Dimension(1365, 765));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGN IN TO ACCOUNT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        cmbSelectStudentEmployee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Employee" }));
        cmbSelectStudentEmployee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectStudentEmployeeItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbSelectStudentEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 260, 40));

        lblStudentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblStudentNoActionPerformed(evt);
            }
        });
        jPanel2.add(lblStudentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 260, 40));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 260, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration_system/plm_logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 150, 140));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SELECT ACCESS");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        lblStudentEmployee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStudentEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblStudentEmployee.setText("STUDENT NO.");
        jPanel2.add(lblStudentEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        lblErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMessage.setText("INVALID ID");
        jPanel2.add(lblErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 200, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 770));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel10.setText("LUNGSOD NG MAYNILA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 280, 720, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Computerized Registration System");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel12.setText("PAMANTASAN NG");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 550, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("WELCOME TO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 51));
        jLabel14.setText("PAMANTASAN NG");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 51));
        jLabel15.setText("LUNGSOD NG MAYNILA");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registration_system/bg_plm.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 0, 1620, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        smm.strStudentNo = lblStudentNo.getText();
        enw.strStudentNum = lblStudentNo.getText();
        strID = lblStudentNo.getText();
        emm.strLogin = lblStudentNo.getText();
        try{
            //Check the combo box if student of employee
            if("Student".equals(strSelectState)){
                ps = conn.prepareStatement("SELECT student_no FROM oop23.student"
                        + " WHERE student_no = '"+strID
                        + "'");
            }else if("Employee".equals(strSelectState)){
                ps = conn.prepareStatement("SELECT employee_id FROM oop23.employee"
                        + " WHERE employee_id = '"+strID
                        + "'");
            }
            rs = ps.executeQuery();
            if(rs.next()){
                if("Student".equals(strSelectState)){
                    if(strID.equals(rs.getString("student_no"))){
                        //Open the Student Main Menu
                        smm.setVisible(true);
                    }
                }
                else if ("Employee".equals(strSelectState)){
                    if(strID.equals(rs.getString("employee_id"))){
                        //Open the Employee Main Menu
                        emm.setVisible(true);
                    }
                }
            }else{
                    lblErrorMessage.setVisible(true);
                }
        }catch(Exception e) {
                System.out.println(e);
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblErrorMessage.setVisible(false);
        strSelectState = cmbSelectStudentEmployee.getSelectedItem().toString();
        
    }//GEN-LAST:event_formWindowOpened

    private void cmbSelectStudentEmployeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectStudentEmployeeItemStateChanged
        // TODO add your handling code here:
        lblErrorMessage.setVisible(false);
        strSelectState = cmbSelectStudentEmployee.getSelectedItem().toString();
        if(strSelectState.equals("Employee")){
            lblStudentEmployee.setText("EMPLOYEE ID.");
        }else if(strSelectState.equals("Student")){
            lblStudentEmployee.setText("STUDENT NO.");
        }
        lblStudentNo.setText("");
    }//GEN-LAST:event_cmbSelectStudentEmployeeItemStateChanged

    private void lblStudentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblStudentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStudentNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbSelectStudentEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblStudentEmployee;
    private javax.swing.JTextField lblStudentNo;
    // End of variables declaration//GEN-END:variables
}
